---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(arrow)
library(geojsonR)
library(rgdal)
library(spdep)
library(tmap)
library(sf)
library(sp)
library(ggplot2)
library(spatialreg)
```


```{r}
db99 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_1999.feather')
db00 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2000.feather')
db01 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2001.feather')
db02 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2002.feather')
db03 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2003.feather')
db04 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2004.feather')
db05 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2005.feather')
db06 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2006.feather')
db07 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2007.feather')
db08 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2008.feather')
db09 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2009.feather')
db10 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2010.feather')
db11 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2011.feather')
db12 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2012.feather')
db13 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2013.feather')
db14 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2014.feather')
db15 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2015.feather')
db16 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2016.feather')
db17 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2017.feather')
db18 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2018.feather')
db19 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2019.feather')
db20 <- read_feather('/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2020.feather')
```
```{r}
library(leaps)
library(arm)
library(lmtest)
library(pROC)
```


```{r}
install.packages('magrittr')
library(magrittr)
```
```{r}
URL <- "http://static.lib.virginia.edu/statlab/materials/data/depression.csv"
dat <- read.csv(URL, stringsAsFactors = TRUE)
dat$id <- factor(dat$id)
dat$drug <- relevel(dat$drug, ref = "standard")
head(dat, n = 3)

```
```{r}
with(dat, tapply(depression, list(diagnose, drug, time), mean)) %>% 
  ftable() %>% 
  round(2)
```
```{r}
install.packages("gee")
```


```{r}
coords_db01 <- cbind(db01$e,db01$n)
nb.dist.band_db01 <- dnearneigh(coords_db01, 0, 600)
dist.listw_db01 = nb2listw(nb.dist.band_db01)
listw01 = dist.listw_db01
dist.band.card_db01 <- card(nb.dist.band_db01)
```
```{r}
coords_db14 <- cbind(db14$e,db14$n)
nb.dist.band_db14 <- dnearneigh(coords_db14, 0, 600)
dist.listw_db14 = nb2listw(nb.dist.band_db14)
listw01 = dist.listw_db01
dist.band.card_db01 <- card(nb.dist.band_db01)
```

```{r}
coords_db18 <- cbind(db18$e,db18$n)
nb.dist.band_db18 <- dnearneigh(coords_db18, 0, 600)
dist.listw_db18 = nb2listw(nb.dist.band_db18)
listw18 = dist.listw_db18
dist.band.card_db18 <- card(nb.dist.band_db18)
```

```{r}
display(step(glm(mammo ~ month_invit+rpdens+rappel+city+mammo_lag+day_invit+groupeage+income_ss+center_density+center_nearest+deprivation_pca, data = db18,family = binomial), trace = F, direction = "both"))
```
```{r}
display(step(glm(mammo ~ month_invit+rpdens+rappel+city+mammo_lag+day_invit+groupeage+income_ss+center_density+center_nearest+deprivation_pca, data = db01,family = binomial), trace = F, direction = "both"))
```

```{r}
#Univariate models
reg.eq0 = mammo ~ income_ss
reg.eq1 = mammo ~ income_ss + deprivation_pca + center_density + center_nearest
```

```{r}
reg1.db14.eq0 <- glm(reg.eq0, data = db14, family = binomial)
reg1.db14.eq1 <- glm(reg.eq1, data = db14, family = binomial)
```

```{r}
lrtest(reg1.db14.eq0, reg1.db14.eq1)
lrtest(reg1.db14.eq1, reg1.db14.eq2)
```
```{r}
plot(regsubsets(mammo ~  month_invit+rpdens+rappel+mammo_lag+day_invit+groupeage+income_ss+center_density+center_nearest+deprivation_pca, data = db14, really.big = T,method = "exhaustive", nbest = 1))
```
```{r}
reg.eq2 = mammo ~ mammo_lag+rappel+rpdens+income_ss+groupeage+center_density+deprivation_pca

reg1.db14.eq2 <- standardize(glm(mammo ~ mammo_lag+rappel+rpdens+income_ss+groupeage+center_density+deprivation_pca, data = db14, family = binomial))
reg1.db14.eq3 <- standardize(glm(
    mammo ~ mammo_lag+rappel+rpdens+month_invit+groupeage+center_density+income_ss, data = db14, family = binomial)
  )
display(reg1.db14.eq2)
```
```{r}
exp(coefficients(reg1.db14.eq2))
```

```{r}
binnedplot(fitted(reg1.db14.eq2), 
           residuals(reg1.db14.eq2, type = "response"), 
           nclass = NULL, 
           xlab = "Expected Values", 
           ylab = "Average residual", 
           main = "Binned residual plot", 
           cex.pts = 0.8, 
           col.pts = 1, 
           col.int = "gray")
```

```{r}
invisible(plot(roc(db14$mammo,
                   fitted(reg1.db14.eq1)),
               col = "red", 
               main = "ROC curves: logistic model 1 (red) vs. logistic model 2 (blue)"))
invisible(plot(roc(db14$mammo,
                   fitted(reg1.db14.eq2)),
               print.auc = F, 
               col = "blue", 
               add = T))
invisible(plot(roc(db14$mammo,
                   fitted(reg1.db14.eq3)),
               print.auc = T, 
               col = "green", 
               add = T))
```
```{r}
reg1.db99.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db99, family = binomial))
reg1.db00.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db00, family = binomial))
reg1.db01.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db01, family = binomial))
reg1.db02.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db02, family = binomial))
reg1.db03.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db03, family = binomial))
reg1.db04.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db04, family = binomial))
reg1.db05.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db05, family = binomial))
reg1.db06.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db06, family = binomial))
reg1.db07.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db07, family = binomial))
reg1.db08.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db08, family = binomial))
reg1.db09.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db09, family = binomial))
reg1.db10.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db10, family = binomial))
reg1.db11.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db11, family = binomial))
reg1.db12.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db12, family = binomial))
reg1.db13.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db13, family = binomial))
reg1.db14.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db14, family = binomial))
reg1.db15.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db15, family = binomial))
reg1.db16.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db16, family = binomial))
reg1.db17.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db17, family = binomial))
reg1.db18.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db18, family = binomial))
reg1.db19.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db19, family = binomial))
reg1.db20.eq0 <- standardize(glm(mammo ~ mammo_lag+rappel+month_invit+groupeage+center_density+income_ss+deprivation_pca, data = db20, family = binomial))

```
```{r}
reg1.db99.eq1 <- (glm(mammo ~ mammo_lag, data = db99, family = binomial))
reg1.db00.eq1 <- (glm(mammo ~ mammo_lag, data = db00, family = binomial))
reg1.db01.eq1 <- (glm(mammo ~ mammo_lag, data = db01, family = binomial))
reg1.db02.eq1 <- (glm(mammo ~ mammo_lag, data = db02, family = binomial))
reg1.db03.eq1 <- (glm(mammo ~ mammo_lag, data = db03, family = binomial))
reg1.db04.eq1 <- (glm(mammo ~ mammo_lag, data = db04, family = binomial))
reg1.db05.eq1 <- (glm(mammo ~ mammo_lag, data = db05, family = binomial))
reg1.db06.eq1 <- (glm(mammo ~ mammo_lag, data = db06, family = binomial))
reg1.db07.eq1 <- (glm(mammo ~ mammo_lag, data = db07, family = binomial))
reg1.db08.eq1 <- (glm(mammo ~ mammo_lag, data = db08, family = binomial))
reg1.db09.eq1 <- (glm(mammo ~ mammo_lag, data = db09, family = binomial))
reg1.db10.eq1 <- (glm(mammo ~ mammo_lag, data = db10, family = binomial))
reg1.db11.eq1 <- (glm(mammo ~ mammo_lag, data = db11, family = binomial))
reg1.db12.eq1 <- (glm(mammo ~ mammo_lag, data = db12, family = binomial))
reg1.db13.eq1 <- (glm(mammo ~ mammo_lag, data = db13, family = binomial))
reg1.db14.eq1 <- (glm(mammo ~ mammo_lag, data = db14, family = binomial))
reg1.db15.eq1 <- (glm(mammo ~ mammo_lag, data = db15, family = binomial))
reg1.db16.eq1 <- (glm(mammo ~ mammo_lag, data = db16, family = binomial))
reg1.db17.eq1 <- (glm(mammo ~ mammo_lag, data = db17, family = binomial))
reg1.db18.eq1 <- (glm(mammo ~ mammo_lag, data = db18, family = binomial))
reg1.db19.eq1 <- (glm(mammo ~ mammo_lag, data = db19, family = binomial))
reg1.db20.eq1 <- (glm(mammo ~ mammo_lag, data = db20, family = binomial))

reg1.db99.eq2 <- standardize(glm(mammo ~ income_ss, data = db99, family = binomial))
reg1.db00.eq2 <- standardize(glm(mammo ~ income_ss, data = db00, family = binomial))
reg1.db01.eq2 <- standardize(glm(mammo ~ income_ss, data = db01, family = binomial))
reg1.db02.eq2 <- standardize(glm(mammo ~ income_ss, data = db02, family = binomial))
reg1.db03.eq2 <- standardize(glm(mammo ~ income_ss, data = db03, family = binomial))
reg1.db04.eq2 <- standardize(glm(mammo ~ income_ss, data = db04, family = binomial))
reg1.db05.eq2 <- standardize(glm(mammo ~ income_ss, data = db05, family = binomial))
reg1.db06.eq2 <- standardize(glm(mammo ~ income_ss, data = db06, family = binomial))
reg1.db07.eq2 <- standardize(glm(mammo ~ income_ss, data = db07, family = binomial))
reg1.db08.eq2 <- standardize(glm(mammo ~ income_ss, data = db08, family = binomial))
reg1.db09.eq2 <- standardize(glm(mammo ~ income_ss, data = db09, family = binomial))
reg1.db10.eq2 <- standardize(glm(mammo ~ income_ss, data = db10, family = binomial))
reg1.db11.eq2 <- standardize(glm(mammo ~ income_ss, data = db11, family = binomial))
reg1.db12.eq2 <- standardize(glm(mammo ~ income_ss, data = db12, family = binomial))
reg1.db13.eq2 <- standardize(glm(mammo ~ income_ss, data = db13, family = binomial))
reg1.db14.eq2 <- standardize(glm(mammo ~ income_ss, data = db14, family = binomial))
reg1.db15.eq2 <- standardize(glm(mammo ~ income_ss, data = db15, family = binomial))
reg1.db16.eq2 <- standardize(glm(mammo ~ income_ss, data = db16, family = binomial))
reg1.db17.eq2 <- standardize(glm(mammo ~ income_ss, data = db17, family = binomial))
reg1.db18.eq2 <- standardize(glm(mammo ~ income_ss, data = db18, family = binomial))
reg1.db19.eq2 <- standardize(glm(mammo ~ income_ss, data = db19, family = binomial))
reg1.db20.eq2 <- standardize(glm(mammo ~ income_ss, data = db20, family = binomial))



reg1.db99.eq3 <- (glm(mammo ~ groupeage, data = db99, family = binomial))
reg1.db00.eq3 <- (glm(mammo ~ groupeage, data = db00, family = binomial))
reg1.db01.eq3 <- (glm(mammo ~ groupeage, data = db01, family = binomial))
reg1.db02.eq3 <- (glm(mammo ~ groupeage, data = db02, family = binomial))
reg1.db03.eq3 <- (glm(mammo ~ groupeage, data = db03, family = binomial))
reg1.db04.eq3 <- (glm(mammo ~ groupeage, data = db04, family = binomial))
reg1.db05.eq3 <- (glm(mammo ~ groupeage, data = db05, family = binomial))
reg1.db06.eq3 <- (glm(mammo ~ groupeage, data = db06, family = binomial))
reg1.db07.eq3 <- (glm(mammo ~ groupeage, data = db07, family = binomial))
reg1.db08.eq3 <- (glm(mammo ~ groupeage, data = db08, family = binomial))
reg1.db09.eq3 <- (glm(mammo ~ groupeage, data = db09, family = binomial))
reg1.db10.eq3 <- (glm(mammo ~ groupeage, data = db10, family = binomial))
reg1.db11.eq3 <- (glm(mammo ~ groupeage, data = db11, family = binomial))
reg1.db12.eq3 <- (glm(mammo ~ groupeage, data = db12, family = binomial))
reg1.db13.eq3 <- (glm(mammo ~ groupeage, data = db13, family = binomial))
reg1.db14.eq3 <- (glm(mammo ~ groupeage, data = db14, family = binomial))
reg1.db15.eq3 <- (glm(mammo ~ groupeage, data = db15, family = binomial))
reg1.db16.eq3 <- (glm(mammo ~ groupeage, data = db16, family = binomial))
reg1.db17.eq3 <- (glm(mammo ~ groupeage, data = db17, family = binomial))
reg1.db18.eq3 <- (glm(mammo ~ groupeage, data = db18, family = binomial))
reg1.db19.eq3 <- (glm(mammo ~ groupeage, data = db19, family = binomial))
reg1.db20.eq3 <- (glm(mammo ~ groupeage, data = db20, family = binomial))

reg1.db99.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db99, family = binomial))
reg1.db00.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db00, family = binomial))
reg1.db01.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db01, family = binomial))
reg1.db02.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db02, family = binomial))
reg1.db03.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db03, family = binomial))
reg1.db04.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db04, family = binomial))
reg1.db05.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db05, family = binomial))
reg1.db06.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db06, family = binomial))
reg1.db07.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db07, family = binomial))
reg1.db08.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db08, family = binomial))
reg1.db09.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db09, family = binomial))
reg1.db10.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db10, family = binomial))
reg1.db11.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db11, family = binomial))
reg1.db12.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db12, family = binomial))
reg1.db13.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db13, family = binomial))
reg1.db14.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db14, family = binomial))
reg1.db15.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db15, family = binomial))
reg1.db16.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db16, family = binomial))
reg1.db17.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db17, family = binomial))
reg1.db18.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db18, family = binomial))
reg1.db19.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db19, family = binomial))
reg1.db20.eq4 <- standardize(glm(mammo ~ deprivation_pca, data = db20, family = binomial))


reg1.db99.eq5 <- (glm(mammo ~ month_invit, data = db99, family = binomial))
reg1.db00.eq5 <- (glm(mammo ~ month_invit, data = db00, family = binomial))
reg1.db01.eq5 <- (glm(mammo ~ month_invit, data = db01, family = binomial))
reg1.db02.eq5 <- (glm(mammo ~ month_invit, data = db02, family = binomial))
reg1.db03.eq5 <- (glm(mammo ~ month_invit, data = db03, family = binomial))
reg1.db04.eq5 <- (glm(mammo ~ month_invit, data = db04, family = binomial))
reg1.db05.eq5 <- (glm(mammo ~ month_invit, data = db05, family = binomial))
reg1.db06.eq5 <- (glm(mammo ~ month_invit, data = db06, family = binomial))
reg1.db07.eq5 <- (glm(mammo ~ month_invit, data = db07, family = binomial))
reg1.db08.eq5 <- (glm(mammo ~ month_invit, data = db08, family = binomial))
reg1.db09.eq5 <- (glm(mammo ~ month_invit, data = db09, family = binomial))
reg1.db10.eq5 <- (glm(mammo ~ month_invit, data = db10, family = binomial))
reg1.db11.eq5 <- (glm(mammo ~ month_invit, data = db11, family = binomial))
reg1.db12.eq5 <- (glm(mammo ~ month_invit, data = db12, family = binomial))
reg1.db13.eq5 <- (glm(mammo ~ month_invit, data = db13, family = binomial))
reg1.db14.eq5 <- (glm(mammo ~ month_invit, data = db14, family = binomial))
reg1.db15.eq5 <- (glm(mammo ~ month_invit, data = db15, family = binomial))
reg1.db16.eq5 <- (glm(mammo ~ month_invit, data = db16, family = binomial))
reg1.db17.eq5 <- (glm(mammo ~ month_invit, data = db17, family = binomial))
reg1.db18.eq5 <- (glm(mammo ~ month_invit, data = db18, family = binomial))
reg1.db19.eq5 <- (glm(mammo ~ month_invit, data = db19, family = binomial))
reg1.db20.eq5 <- (glm(mammo ~ month_invit, data = db20, family = binomial))

reg1.db99.eq6 <- (glm(mammo ~ center_density, data = db99, family = binomial))
reg1.db00.eq6 <- (glm(mammo ~ center_density, data = db00, family = binomial))
reg1.db01.eq6 <- (glm(mammo ~ center_density, data = db01, family = binomial))
reg1.db02.eq6 <- (glm(mammo ~ center_density, data = db02, family = binomial))
reg1.db03.eq6 <- (glm(mammo ~ center_density, data = db03, family = binomial))
reg1.db04.eq6 <- (glm(mammo ~ center_density, data = db04, family = binomial))
reg1.db05.eq6 <- (glm(mammo ~ center_density, data = db05, family = binomial))
reg1.db06.eq6 <- (glm(mammo ~ center_density, data = db06, family = binomial))
reg1.db07.eq6 <- (glm(mammo ~ center_density, data = db07, family = binomial))
reg1.db08.eq6 <- (glm(mammo ~ center_density, data = db08, family = binomial))
reg1.db09.eq6 <- (glm(mammo ~ center_density, data = db09, family = binomial))
reg1.db10.eq6 <- (glm(mammo ~ center_density, data = db10, family = binomial))
reg1.db11.eq6 <- (glm(mammo ~ center_density, data = db11, family = binomial))
reg1.db12.eq6 <- (glm(mammo ~ center_density, data = db12, family = binomial))
reg1.db13.eq6 <- (glm(mammo ~ center_density, data = db13, family = binomial))
reg1.db14.eq6 <- (glm(mammo ~ center_density, data = db14, family = binomial))
reg1.db15.eq6 <- (glm(mammo ~ center_density, data = db15, family = binomial))
reg1.db16.eq6 <- (glm(mammo ~ center_density, data = db16, family = binomial))
reg1.db17.eq6 <- (glm(mammo ~ center_density, data = db17, family = binomial))
reg1.db18.eq6 <- (glm(mammo ~ center_density, data = db18, family = binomial))
reg1.db19.eq6 <- (glm(mammo ~ center_density, data = db19, family = binomial))
reg1.db20.eq6 <- (glm(mammo ~ center_density, data = db20, family = binomial))

```

```{r}
library(jtools)
library(ggstance)
library(broom.mixed)
```
```{r}
plot_summs(reg1.db05.eq0,reg1.db13.eq0,reg1.db18.eq0,reg1.db20.eq0, exp = T,model.names = c("2005","2013","2018","2020"),inner_ci_level = .90)
```
```{r}
plot_summs(reg1.db13.eq0,reg1.db14.eq0,reg1.db15.eq0,reg1.db16.eq0,reg1.db17.eq0,reg1.db18.eq0, exp = T,model.names = c("2013","2014","2015","2016","2017","2018"),inner_ci_level = .90)
```

```{r}
plot_summs(reg1.db03.eq1,reg1.db05.eq1,reg1.db11.eq1,reg1.db15.eq1,reg1.db18.eq1,reg1.db20.eq1, exp = T,model.names = c("2003","2005","2011","2015","2018","2020"),inner_ci_level = .90)
```

```{r}
plot_summs(reg1.db03.eq2,reg1.db05.eq2,reg1.db11.eq2,reg1.db15.eq2,reg1.db18.eq2,reg1.db20.eq2, exp = T,model.names = c("2003","2005","2011","2015", "2018","2020"),inner_ci_level = .90)
```

```{r}
plot_summs(reg1.db03.eq3,reg1.db05.eq3,reg1.db11.eq3,reg1.db15.eq3,reg1.db18.eq3,reg1.db20.eq3, exp = T,model.names = c("2003","2005","2011","2015", "2018","2020"),scale = T,ci_level = 0, inner_ci_level = 0)
```

```{r}
help(plot_summs)
plot_summs(reg1.db03.eq4,reg1.db05.eq4,reg1.db11.eq4,reg1.db15.eq4,reg1.db18.eq4,reg1.db20.eq4, exp = T, model.names = c("2003","2005","2011","2015", "2018","2020"),scale = T,inner_ci_level = .90)
```
```{r}
plot_summs(reg1.db03.eq5,reg1.db05.eq5,reg1.db11.eq5,reg1.db15.eq5,reg1.db18.eq5,reg1.db20.eq5, exp = T, model.names = c("2003","2005","2011","2015", "2018","2020"),inner_ci_level = .90)
```
```{r}
plot_summs(reg1.db03.eq6,reg1.db05.eq6,reg1.db11.eq6,reg1.db15.eq6,reg1.db18.eq6,reg1.db20.eq6, exp = T, model.names = c("2003","2005","2011","2015", "2018","2020"),inner_ci_level = .90)
```

```{r}
install.packages('huxtable')
library(huxtable)
export_summs(reg1.db13.eq1, reg1.db13.eq2, scale = TRUE)

```


```{r}
db99$resid0 <- residuals(reg1.db99.eq0, type = "pearson")
db00$resid0 <- residuals(reg1.db00.eq0, type = "pearson")
db01$resid0 <- residuals(reg1.db01.eq0, type = "pearson")
db02$resid0 <- residuals(reg1.db02.eq0, type = "pearson")
db03$resid0 <- residuals(reg1.db03.eq0, type = "pearson")
db04$resid0 <- residuals(reg1.db04.eq0, type = "pearson")
db05$resid0 <- residuals(reg1.db05.eq0, type = "pearson")
db06$resid0 <- residuals(reg1.db06.eq0, type = "pearson")
db07$resid0 <- residuals(reg1.db07.eq0, type = "pearson")
db08$resid0 <- residuals(reg1.db08.eq0, type = "pearson")
db09$resid0 <- residuals(reg1.db09.eq0, type = "pearson")
db10$resid0 <- residuals(reg1.db10.eq0, type = "pearson")
db11$resid0 <- residuals(reg1.db11.eq0, type = "pearson")
db12$resid0 <- residuals(reg1.db12.eq0, type = "pearson")
db13$resid0 <- residuals(reg1.db13.eq0, type = "pearson")
db14$resid0 <- residuals(reg1.db14.eq0, type = "pearson")
db15$resid0 <- residuals(reg1.db15.eq0, type = "pearson")
db16$resid0 <- residuals(reg1.db16.eq0, type = "pearson")
db17$resid0 <- residuals(reg1.db17.eq0, type = "pearson")
db18$resid0 <- residuals(reg1.db18.eq0, type = "pearson")
db19$resid0 <- residuals(reg1.db19.eq0, type = "pearson")
db20$resid0 <- residuals(reg1.db20.eq0, type = "pearson")

db99$resid1 <- residuals(reg1.db99.eq1, type = "pearson")
db00$resid1 <- residuals(reg1.db00.eq1, type = "pearson")
db01$resid1 <- residuals(reg1.db01.eq1, type = "pearson")
db02$resid1 <- residuals(reg1.db02.eq1, type = "pearson")
db03$resid1 <- residuals(reg1.db03.eq1, type = "pearson")
db04$resid1 <- residuals(reg1.db04.eq1, type = "pearson")
db05$resid1 <- residuals(reg1.db05.eq1, type = "pearson")
db06$resid1 <- residuals(reg1.db06.eq1, type = "pearson")
db07$resid1 <- residuals(reg1.db07.eq1, type = "pearson")
db08$resid1 <- residuals(reg1.db08.eq1, type = "pearson")
db09$resid1 <- residuals(reg1.db09.eq1, type = "pearson")
db10$resid1 <- residuals(reg1.db10.eq1, type = "pearson")
db11$resid1 <- residuals(reg1.db11.eq1, type = "pearson")
db12$resid1 <- residuals(reg1.db12.eq1, type = "pearson")
db13$resid1 <- residuals(reg1.db13.eq1, type = "pearson")
db14$resid1 <- residuals(reg1.db14.eq1, type = "pearson")
db15$resid1 <- residuals(reg1.db15.eq1, type = "pearson")
db16$resid1 <- residuals(reg1.db16.eq1, type = "pearson")
db17$resid1 <- residuals(reg1.db17.eq1, type = "pearson")
db18$resid1 <- residuals(reg1.db18.eq1, type = "pearson")
db19$resid1 <- residuals(reg1.db19.eq1, type = "pearson")
db20$resid1 <- residuals(reg1.db20.eq1, type = "pearson")

db99$resid2 <- residuals(reg1.db99.eq2, type = "pearson")
db00$resid2 <- residuals(reg1.db00.eq2, type = "pearson")
db01$resid2 <- residuals(reg1.db01.eq2, type = "pearson")
db02$resid2 <- residuals(reg1.db02.eq2, type = "pearson")
db03$resid2 <- residuals(reg1.db03.eq2, type = "pearson")
db04$resid2 <- residuals(reg1.db04.eq2, type = "pearson")
db05$resid2 <- residuals(reg1.db05.eq2, type = "pearson")
db06$resid2 <- residuals(reg1.db06.eq2, type = "pearson")
db07$resid2 <- residuals(reg1.db07.eq2, type = "pearson")
db08$resid2 <- residuals(reg1.db08.eq2, type = "pearson")
db09$resid2 <- residuals(reg1.db09.eq2, type = "pearson")
db10$resid2 <- residuals(reg1.db10.eq2, type = "pearson")
db11$resid2 <- residuals(reg1.db11.eq2, type = "pearson")
db12$resid2 <- residuals(reg1.db12.eq2, type = "pearson")
db13$resid2 <- residuals(reg1.db13.eq2, type = "pearson")
db14$resid2 <- residuals(reg1.db14.eq2, type = "pearson")
db15$resid2 <- residuals(reg1.db15.eq2, type = "pearson")
db16$resid2 <- residuals(reg1.db16.eq2, type = "pearson")
db17$resid2 <- residuals(reg1.db17.eq2, type = "pearson")
db18$resid2 <- residuals(reg1.db18.eq2, type = "pearson")
db19$resid2 <- residuals(reg1.db19.eq2, type = "pearson")
db20$resid2 <- residuals(reg1.db20.eq2, type = "pearson")

db99$resid3 <- residuals(reg1.db99.eq3, type = "pearson")
db00$resid3 <- residuals(reg1.db00.eq3, type = "pearson")
db01$resid3 <- residuals(reg1.db01.eq3, type = "pearson")
db02$resid3 <- residuals(reg1.db02.eq3, type = "pearson")
db03$resid3 <- residuals(reg1.db03.eq3, type = "pearson")
db04$resid3 <- residuals(reg1.db04.eq3, type = "pearson")
db05$resid3 <- residuals(reg1.db05.eq3, type = "pearson")
db06$resid3 <- residuals(reg1.db06.eq3, type = "pearson")
db07$resid3 <- residuals(reg1.db07.eq3, type = "pearson")
db08$resid3 <- residuals(reg1.db08.eq3, type = "pearson")
db09$resid3 <- residuals(reg1.db09.eq3, type = "pearson")
db10$resid3 <- residuals(reg1.db10.eq3, type = "pearson")
db11$resid3 <- residuals(reg1.db11.eq3, type = "pearson")
db12$resid3 <- residuals(reg1.db12.eq3, type = "pearson")
db13$resid3 <- residuals(reg1.db13.eq3, type = "pearson")
db14$resid3 <- residuals(reg1.db14.eq3, type = "pearson")
db15$resid3 <- residuals(reg1.db15.eq3, type = "pearson")
db16$resid3 <- residuals(reg1.db16.eq3, type = "pearson")
db17$resid3 <- residuals(reg1.db17.eq3, type = "pearson")
db18$resid3 <- residuals(reg1.db18.eq3, type = "pearson")
db19$resid3 <- residuals(reg1.db19.eq3, type = "pearson")
db20$resid3 <- residuals(reg1.db20.eq3, type = "pearson")

db99$resid4 <- residuals(reg1.db99.eq4, type = "pearson")
db00$resid4 <- residuals(reg1.db00.eq4, type = "pearson")
db01$resid4 <- residuals(reg1.db01.eq4, type = "pearson")
db02$resid4 <- residuals(reg1.db02.eq4, type = "pearson")
db03$resid4 <- residuals(reg1.db03.eq4, type = "pearson")
db04$resid4 <- residuals(reg1.db04.eq4, type = "pearson")
db05$resid4 <- residuals(reg1.db05.eq4, type = "pearson")
db06$resid4 <- residuals(reg1.db06.eq4, type = "pearson")
db07$resid4 <- residuals(reg1.db07.eq4, type = "pearson")
db08$resid4 <- residuals(reg1.db08.eq4, type = "pearson")
db09$resid4 <- residuals(reg1.db09.eq4, type = "pearson")
db10$resid4 <- residuals(reg1.db10.eq4, type = "pearson")
db11$resid4 <- residuals(reg1.db11.eq4, type = "pearson")
db12$resid4 <- residuals(reg1.db12.eq4, type = "pearson")
db13$resid4 <- residuals(reg1.db13.eq4, type = "pearson")
db14$resid4 <- residuals(reg1.db14.eq4, type = "pearson")
db15$resid4 <- residuals(reg1.db15.eq4, type = "pearson")
db16$resid4 <- residuals(reg1.db16.eq4, type = "pearson")
db17$resid4 <- residuals(reg1.db17.eq4, type = "pearson")
db18$resid4 <- residuals(reg1.db18.eq4, type = "pearson")
db19$resid4 <- residuals(reg1.db19.eq4, type = "pearson")
db20$resid4 <- residuals(reg1.db20.eq4, type = "pearson")

db99$resid5 <- residuals(reg1.db99.eq5, type = "pearson")
db00$resid5 <- residuals(reg1.db00.eq5, type = "pearson")
db01$resid5 <- residuals(reg1.db01.eq5, type = "pearson")
db02$resid5 <- residuals(reg1.db02.eq5, type = "pearson")
db03$resid5 <- residuals(reg1.db03.eq5, type = "pearson")
db04$resid5 <- residuals(reg1.db04.eq5, type = "pearson")
db05$resid5 <- residuals(reg1.db05.eq5, type = "pearson")
db06$resid5 <- residuals(reg1.db06.eq5, type = "pearson")
db07$resid5 <- residuals(reg1.db07.eq5, type = "pearson")
db08$resid5 <- residuals(reg1.db08.eq5, type = "pearson")
db09$resid5 <- residuals(reg1.db09.eq5, type = "pearson")
db10$resid5 <- residuals(reg1.db10.eq5, type = "pearson")
db11$resid5 <- residuals(reg1.db11.eq5, type = "pearson")
db12$resid5 <- residuals(reg1.db12.eq5, type = "pearson")
db13$resid5 <- residuals(reg1.db13.eq5, type = "pearson")
db14$resid5 <- residuals(reg1.db14.eq5, type = "pearson")
db15$resid5 <- residuals(reg1.db15.eq5, type = "pearson")
db16$resid5 <- residuals(reg1.db16.eq5, type = "pearson")
db17$resid5 <- residuals(reg1.db17.eq5, type = "pearson")
db18$resid5 <- residuals(reg1.db18.eq5, type = "pearson")
db19$resid5 <- residuals(reg1.db19.eq5, type = "pearson")
db20$resid5 <- residuals(reg1.db20.eq5, type = "pearson")

db99$resid6 <- residuals(reg1.db99.eq6, type = "pearson")
db00$resid6 <- residuals(reg1.db00.eq6, type = "pearson")
db01$resid6 <- residuals(reg1.db01.eq6, type = "pearson")
db02$resid6 <- residuals(reg1.db02.eq6, type = "pearson")
db03$resid6 <- residuals(reg1.db03.eq6, type = "pearson")
db04$resid6 <- residuals(reg1.db04.eq6, type = "pearson")
db05$resid6 <- residuals(reg1.db05.eq6, type = "pearson")
db06$resid6 <- residuals(reg1.db06.eq6, type = "pearson")
db07$resid6 <- residuals(reg1.db07.eq6, type = "pearson")
db08$resid6 <- residuals(reg1.db08.eq6, type = "pearson")
db09$resid6 <- residuals(reg1.db09.eq6, type = "pearson")
db10$resid6 <- residuals(reg1.db10.eq6, type = "pearson")
db11$resid6 <- residuals(reg1.db11.eq6, type = "pearson")
db12$resid6 <- residuals(reg1.db12.eq6, type = "pearson")
db13$resid6 <- residuals(reg1.db13.eq6, type = "pearson")
db14$resid6 <- residuals(reg1.db14.eq6, type = "pearson")
db15$resid6 <- residuals(reg1.db15.eq6, type = "pearson")
db16$resid6 <- residuals(reg1.db16.eq6, type = "pearson")
db17$resid6 <- residuals(reg1.db17.eq6, type = "pearson")
db18$resid6 <- residuals(reg1.db18.eq6, type = "pearson")
db19$resid6 <- residuals(reg1.db19.eq6, type = "pearson")
db20$resid6 <- residuals(reg1.db20.eq6, type = "pearson")

```

```{r}
write_feather(db99, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_1999_wres.feather')
write_feather(db00, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2000_wres.feather')
write_feather(db01, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2001_wres.feather')
write_feather(db02, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2002_wres.feather')
write_feather(db03, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2003_wres.feather')
write_feather(db04, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2004_wres.feather')
write_feather(db05, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2005_wres.feather')
write_feather(db06, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2006_wres.feather')
write_feather(db07, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2007_wres.feather')
write_feather(db08, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2008_wres.feather')
write_feather(db09, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2009_wres.feather')
write_feather(db10, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2010_wres.feather')
write_feather(db11, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2011_wres.feather')
write_feather(db12, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2012_wres.feather')
write_feather(db13, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2013_wres.feather')
write_feather(db14, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2014_wres.feather')
write_feather(db15, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2015_wres.feather')
write_feather(db16, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2016_wres.feather')
write_feather(db17, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2017_wres.feather')
write_feather(db18, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2018_wres.feather')
write_feather(db19, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2019_wres.feather')
write_feather(db20, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Data/Processed data/Yearly datasets/GIRACS_participation_2020_wres.feather')

```

```{r}
library(rgdal)
writeOGR(db99, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_1999_wres.geojson', "GIRACS_participation_1999_wres", driver="GeoJSON")
writeOGR(db00, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2000_wres.geojson', "GIRACS_participation_2000_wres", driver="GeoJSON")
writeOGR(db01, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2001_wres.geojson', "GIRACS_participation_2001_wres", driver="GeoJSON")
writeOGR(db02, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2002_wres.geojson', "GIRACS_participation_2002_wres", driver="GeoJSON")
writeOGR(db03, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2003_wres.geojson', "GIRACS_participation_2003_wres", driver="GeoJSON")
writeOGR(db04, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2004_wres.geojson', "GIRACS_participation_2004_wres", driver="GeoJSON")
writeOGR(db05, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2005_wres.geojson', "GIRACS_participation_2005_wres", driver="GeoJSON")
writeOGR(db06, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2006_wres.geojson', "GIRACS_participation_2006_wres", driver="GeoJSON")
writeOGR(db07, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2007_wres.geojson', "GIRACS_participation_2007_wres", driver="GeoJSON")
writeOGR(db08, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2008_wres.geojson', "GIRACS_participation_2008_wres", driver="GeoJSON")
writeOGR(db09, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2009_wres.geojson', "GIRACS_participation_2009_wres", driver="GeoJSON")
writeOGR(db10, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2010_wres.geojson', "GIRACS_participation_2010_wres", driver="GeoJSON")
writeOGR(db11, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2011_wres.geojson', "GIRACS_participation_2011_wres", driver="GeoJSON")
writeOGR(db12, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2012_wres.geojson', "GIRACS_participation_2012_wres", driver="GeoJSON")
writeOGR(db13, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2013_wres.geojson', "GIRACS_participation_2013_wres", driver="GeoJSON")
writeOGR(db14, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2014_wres.geojson', "GIRACS_participation_2014_wres", driver="GeoJSON")
writeOGR(db15, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2015_wres.geojson', "GIRACS_participation_2015_wres", driver="GeoJSON")
writeOGR(db16, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2016_wres.geojson', "GIRACS_participation_2016_wres", driver="GeoJSON")
writeOGR(db17, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2017_wres.geojson', "GIRACS_participation_2017_wres", driver="GeoJSON")
writeOGR(db18, '/Users/david/Dropbox/PhD/GitHub/GIRACS/Results/Processed data/Yearly datasets/GIRACS_participation_2018_wres.geojson', "GIRACS_participation_2018_wres", driver="GeoJSON")


```
```{r}
data(oldcol)
HICRIME <- cut(COL.OLD$CRIME, breaks=c(0,35,80), labels=c("low","high"))
db18$mammo_fac <- as.factor(db18$mammo)
reg1.moran.db18.eq0 = lm.morantest(reg1.db18.eq0,listw18)
reg1.jc.db18 =joincount.test(db18$mammo_fac,listw18)
```
```{r}
reg1.lm.db18.eq0 = lm.LMtests(reg1.db18.eq0,listw18,test='all')
```

