---
title: "R Notebook"
output: html_notebook
---
```{r}
install.packages("lme4")
library(lme4)
library(ggeffects)

```

# Tutorial
```{r}
URL <- "http://static.lib.virginia.edu/statlab/materials/data/depression.csv"
dat <- read.csv(URL, stringsAsFactors = TRUE)
dat$id <- factor(dat$id)
dat$drug <- relevel(dat$drug, ref = "standard")
head(dat, n = 3)
```
```{r}
length(unique(dat$id))
```
```{r}
install.packages("magrittr")
library(magrittr)
with(dat, tapply(depression, list(diagnose, drug, time), mean)) %>% 
  ftable() %>% 
  round(2)
```

```{r}
install.packages("gee")
library(gee)
dep_gee <- gee(depression ~ diagnose + drug*time,
               data = dat, 
               id = id, 
               family = binomial,
               corstr = "independence")
summary(dep_gee)
```
```{r}
dep_gee2 <- gee(depression ~ diagnose + drug*time,
               data = dat, 
               id = id, 
               family = binomial,
               corstr = "exchangeable")
summary(dep_gee2)
```

```{r}
dep_gee3 <- gee(depression ~ diagnose + drug*time,
               data = dat, 
               id = id, 
               family = binomial,
               corstr = "AR-M", Mv = 1)

dep_gee3$working.correlation
```
```{r}
dep_glmer <- glmer(depression ~ diagnose + drug*time + (1|id), 
               data = dat, family = binomial)
summary(dep_glmer, corr = FALSE)
```
```{r}
plot(ggemmeans(dep_glmer, terms = c("time", "drug"), 
               condition = c(diagnose = "severe"))) + 
  ggplot2::ggtitle("GLMER Effect plot")
```
```{r}
plot(ggemmeans(dep_gee2, terms = c("time", "drug"),
               condition = c(diagnose = "severe"))) + 
  ggplot2::ggtitle("GEE Effect plot")
```

# Mammography analysis
```{r}
dat_mammo <- read.csv('../Data/mammo_gee_dat.csv', stringsAsFactors = TRUE)
```

```{r}
with(dat_mammo, tapply(mammo, list(deprivation_pca_q5,status, time), mean)) %>% 
  ftable() %>% 
  round(2)
```

```{r}
dep_gee <- gee(mammo ~  deprivation_pca_q5 + status*time,
               data = dat_mammo, 
               id = numerodossier, 
               family = binomial,
               corstr = "independence")
summary(dep_gee)
```
```{r}
# install.packages("ggeffects")
library(ggeffects)
plot(ggemmeans(dep_gee, terms = c("time", "mammo"),
               condition = c(deprivation_pca_q5 = 4))) + 
  ggplot2::ggtitle("GEE Effect plot")
```
```{r}
dat_mammo5 <- read.csv('../Data/mammo_gee_5invit_dat.csv', stringsAsFactors = TRUE)
```
```{r}
with(dat_mammo5, tapply(mammo, list(deprivation_pca_q5,status, numeroinvitation_seq), mean)) %>% 
  ftable() %>% 
  round(2)
```
```{r}
dep_gee <- gee(mammo ~  deprivation_pca_q5 + status*numeroinvitation_seq,
               data = dat_mammo5, 
               id = numerodossier, 
               family = binomial,
               corstr = "independence")
summary(dep_gee)
```


```{r}
help(ggemmeans)
ggemmeans(dep_gee, terms = c("status",))
```

```{r}
plot(ggemmeans(dep_gee, terms = c("numeroinvitation_seq", "status"),
               condition = c(deprivation_pca_q5 = 0))) + 
  ggplot2::ggtitle("GEE Effect plot")
```
```{r}
dep_gee2 <- gee(mammo ~ deprivation_pca_q5 + status*numeroinvitation_seq,
               data = dat_mammo5, 
               id = numerodossier, 
               family = binomial,
               corstr = "exchangeable")
summary(dep_gee2)
```
```{r}
dep_gee3 <- gee(mammo ~ deprivation_pca_q5 + status*numeroinvitation_seq,
               data = dat_mammo5, 
               id = numerodossier, 
               family = binomial,
               corstr = "AR-M", Mv = 1)
dep_gee3$working.correlation

```
```{r}
dep_glmer <- glmer(mammo ~ deprivation_pca_q5 + status*numeroinvitation_seq + (1|numerodossier), 
               data = dat_mammo5, family = binomial)
summary(dep_glmer, corr = FALSE)
```

```{r}
plot(ggemmeans(dep_glmer, terms = c("numeroinvitation_seq", "status"), 
               condition = c(deprivation_pca_q5 = 0))) + 
  ggplot2::ggtitle("GLMER Effect plot")
```
```{r}
plot(ggemmeans(dep_glmer, terms = c("numeroinvitation_seq", "status"), 
               condition = c(deprivation_pca_q5 = 4))) + 
  ggplot2::ggtitle("GLMER Effect plot")
```
```{r}
dat_mammo5_consec <- read.csv('../Data/mammo_gee_5consecutive_invit_dat.csv',stringsAsFactors = TRUE)
dat_mammo5_consec$numerodossier <- factor(dat_mammo5_consec$numerodossier)
dat_mammo5_consec$status <- relevel(dat_mammo5_consec$status, ref = "Non-conducive environment")
```
```{r}
with(dat_mammo5_consec, tapply(mammo, list(deprivation_pca_q5,status, time), mean)) %>% 
  ftable() %>% 
  round(2)

```
```{r}
dep_gee_5consec <- gee(mammo ~  deprivation_pca_q5 + status*time,
               data = dat_mammo5_consec, 
               id = numerodossier, 
               family = binomial,
               corstr = "independence")
summary(dep_gee_5consec)
```

```{r}
dep_gee2 <- gee(mammo ~ deprivation_pca_q5 + status*time,
               data = dat_mammo5_consec, 
               id = numerodossier, 
               family = binomial,
               corstr = "exchangeable")
summary(dep_gee2)
```
```{r}
dep_gee3 <- gee(mammo ~ deprivation_pca_q5 + status*time,
               data = dat_mammo5_consec, 
               id = numerodossier, 
               family = binomial,
               corstr = "AR-M", Mv = 1)
dep_gee3$working.correlation

```
```{r}
dep_glmer <- glmer(mammo ~  deprivation_pca_q5 + time*status + (1|numerodossier), 
               data = dat_mammo5_consec, family = binomial)
summary(dep_glmer, corr = FALSE)
```

```{r}
ggemmeans(dep_glmer, terms = c("time", "status"), 
               condition = c(deprivation_pca_q5 = 0))
plot(ggemmeans(dep_glmer, terms = c("time", "status"), 
               condition = c(deprivation_pca_q5 = 4))) + 
  ggplot2::ggtitle("GLMER Effect plot")
```

```{r}
plot(ggemmeans(dep_glmer, terms = c("time", "status"), 
               condition = c(deprivation_pca_q5 = 0))) + 
  ggplot2::ggtitle("GLMER Effect plot")
```

