---
title: "COVID modelling"
output: html_notebook
---

```{r}
install.packages("MapGAM")
install.packages("PBSmapping")
library("MapGAM")
library("PBSmapping")
```
```{r}
data(MAmap)
data(MAdata)
```


```{r}
gamgrid <- predgrid(MAdata, map=MAmap)  
fit1 <- modgam(data=MAdata, rgrid=gamgrid, m="crude", sp=0.5)  
```
```{r}
# Summary statistics for pointwise crude odds ratios 
summary(fit1$exp.fit)			
# Summary stats for pointwise crude log odds (linear predictor) 
summary(fit1$fit)
```
```{r}
# fit adjusted GAM using span size of 50%, 
# including a (too small) conditional permutation test
fit2 <- modgam(data=MAdata, rgrid=gamgrid, permute=25, m="adjusted", sp=0.5)  
fit2
```
```{r}
# fit adjusted GAM by specifiying formula
fit2.f <- modgam(Case~lo(Xcoord,Ycoord)+Smoking + Mercury + Selenium,data=MAdata,
rgrid=gamgrid, sp=0.5)
fit2.f
```
```{r}
data <- read.csv('/Users/david/Dropbox/PhD/GitHub/COVID19/Data/Clean_data/final_data_indi_level.csv')
Locations = cbind(data$lon, data$lat) # using the sampling locations 
phen <- c("ID", "E", "N","lon","lat","Test.Result","Age","SEXE",'week_test','deprivation_pca') # Base columns with spatial information we'll need
TestCovid <- na.omit(data[, c(phen)]) # Getting rid of NA's, picking adults
TestCovid$week_test <- as.factor(TestCovid$week_test)
TestCovid$deprivation_pca <- -TestCovid$deprivation_pca
library(rgdal)
library(rgeos)
library(sf)
ge_shp <- readOGR(dsn = '/Users/david/Dropbox/PhD/GitHub/COVID19/Data/Mapping/',layer = 'canton_contour_ge')
ge.border <- gUnaryUnion(ge_shp,rep(1,nrow(ge_shp)))
gamgrid <- predgrid(TestCovid, map=ge_shp)
plot(gamgrid)
```
```{r}
fit1 <- modgam(Test.Result ~ lo(E, N),data=TestCovid,sp = 0.15, rgrid=gamgrid, verbose = TRUE,se.fit = TRUE)
fit1
```
```{r}
plot(fit1,ge_shp,contours="interval",exp = TRUE)
```
```{r}
fit2 <- modgam(Test.Result ~ lo(E, N) + week_test,data=TestCovid, rgrid=gamgrid, sp=0.15, verbose = TRUE,se.fit = TRUE)
fit2
```
```{r}
plot(fit2,ge_shp,contours="interval",exp = TRUE)
```
```{r}
fit3 <- modgam(Test.Result ~ lo(E, N) + week_test+Age+SEXE,data=TestCovid, rgrid=gamgrid, sp=0.15, verbose = TRUE,se.fit = TRUE)
fit3
```
```{r}
plot(fit3,ge_shp,contours="interval",exp = TRUE)
```
```{r}
fit4 <- modgam(Test.Result ~ lo(E, N) + week_test+Age+SEXE+deprivation_pca,data=TestCovid, rgrid=gamgrid, sp=0.15, verbose = TRUE,se.fit = TRUE)
fit4
```
```{r}
plot(fit4,ge_shp,contours="interval",exp = TRUE)
```


```{r}
data_sero <- read.csv('/Users/david/Dropbox/PhD/GitHub/COVID19/Data/Clean_data/2020720_sero_indi.csv')
phen <- c("ID", "E", "N","sero_int",'codbar_hh') # Base columns with spatial information we'll need
TestSero <- na.omit(data_sero[, c(phen)]) # Getting rid of NA's, picking adults
TestSero$codbar_hh <- as.factor(TestSero$codbar_hh)

gamgrid_sero <- predgrid(TestSero, map=ge_shp)
plot(gamgrid_sero)
```


```{r}
fit1_sero <- modgam(sero_int ~ lo(E, N),data=TestSero, rgrid=gamgrid_sero, sp=NULL, verbose = FALSE)
fit1_sero
```
```{r}
plot(fit1_sero,ge_shp,contours="response",exp = TRUE)
```

```{r}
fit2_sero <- modgam(sero_int ~ lo(E, N),data=TestSero,sp = 0.05,se.fit = TRUE,permute = 100, rgrid=gamgrid_sero, verbose = TRUE)
fit2_sero
```
```{r}
plot(fit2_sero,ge_shp,contours="interval",exp = TRUE)
```
```{r}
fit3_sero <- modgam(sero_int ~ lo(E, N)+ codbar_hh ,data=TestSero,sp = 0.05,permute = 100,se.fit = TRUE, rgrid=gamgrid_sero, verbose = TRUE)
fit3_sero
```

```{r}
plot(fit3_sero,ge_shp,contours="interval",exp = TRUE)
```

```{r}
obj <- list(grid=data.frame(TestSero$E,TestSero$N),fit=TestSero$rev_brut_med_cpl)
colormap(obj, ge_shp, legend.name = "Income (couple)")
```


```{r}
fit3_sero <- gam(sero_int ~ lo(E, N)+ rev_brut_med_cpl ,data=TestSero,sp = 0.05,permute = 100, rgrid=gamgrid_sero, verbose = TRUE)
```
```{r}
pred1 = mypredict.gam(fit3_sero)
colormap(list(fit=pred1$pred,grid=gamgrid_sero),map=ge_shp)
```

