title: "COVID modelling"
output: html_notebook
---

```{r}
install.packages("MapGAM")
install.packages("PBSmapping")
library("MapGAM")
library("PBSmapping")
```

```{r}
data <- read.csv('./Results/df_1st_1318.csv')
```
```{r}
library(tidyverse)
Locations = cbind(data$X,data$E_shifted, data$N_shifted) # using the sampling locations 
head(data$mammo_rate_q5)
phen <- c("X","E_shifted",'N_shifted',"mammo","groupeage",'etatcivil','year_invit','deprivation_pca','deprivation_pca_q5','mammo_rate_q5') # Base columns with spatial information we'll need
TestMammo <- na.omit(data[, c(phen)]) # Getting rid of NA's, picking adults
TestMammo$year_invit <- TestMammo$year_invit - 1998
TestMammo$groupeage <- as.factor(TestMammo$groupeage)
TestMammo$etatcivil <- as.factor(TestMammo$etatcivil)
TestMammo[TestMammo$localité != "Céligny", ]
TestMammo<- TestMammo %>% 
  rename(
    E = E_shifted,
    N = N_shifted
    )
library(rgdal)
library(rgeos)
library(sf)
ge_shp <- readOGR(dsn = './Data/',layer = 'communes_ge')
ge.border <- gUnaryUnion(ge_shp,rep(1,nrow(ge_shp)))
gamgrid <- predgrid(TestMammo, map=ge_shp,nrow = 50, ncol = 50)
plot(gamgrid)
```
```{r}
# fit adjusted GAM by specifiying formula

fit1_mammo <- modgam(mammo~lo(E,N),data=TestMammo,rgrid=gamgrid, sp=0.05,se.fit = TRUE)
fit1_mammo
```
```{r}
plot(fit1_mammo,exp = TRUE,contours = 'interval')
```

```{r}
sample25000_TestMammo <- TestMammo[sample(nrow(TestMammo), 25000), ]
gamgrid_s <- predgrid(sample25000_TestMammo, map=ge_shp,nrow = 80, ncol = 80)
fit2_mammo <- modgam(mammo~lo(E,N),data=sample25000_TestMammo,rgrid=gamgrid_s,permute = 100, sp=0.05,se.fit = TRUE)
fit2_mammo
```
```{r}
plot(fit2_mammo,exp = TRUE,contours = 'interval')
```
```{r}
fit3_mammo <- modgam(mammo~lo(E,N)+deprivation_pca_q5,data=sample25000_TestMammo,rgrid=gamgrid_s, sp=0.05,se.fit = TRUE)
fit3_mammo
```

```{r}
plot(fit3_mammo,exp = TRUE,contours = 'interval')

```

```{r}
fit4_mammo <- modgam(mammo~lo(E,N)+deprivation_pca,data=sample25000_TestMammo,rgrid=gamgrid_s, sp=0.05,se.fit = TRUE)
fit4_mammo
```

```{r}
plot(fit4_mammo,exp = TRUE,contours = 'interval')

```
```{r}
summary(fit4_mammo$exp.fit)			

```

